const projectList = [
  {
    title: "flaskCompare",
    link: "https://flaskcompare.krzem.dev/",
    code: "https://github.com/krzemGit/flaskCompare",
    design: "https://www.dropbox.com/s/5gmty12vw36cy9z/Flask-compare-mockup-full.jpg?raw=1",
    tech: "Python / Flask / Javascript / SASS / BEM",
    para1: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia doloremque ut ex, itaque omnis optio dolore repellat quam unde accusamus pariatur cupiditate, nihil rerum delectus sed placeat adipisci necessitatibus maxime eum incidunt nulla animi sequi. Quas fuga voluptate magnam odio error laborum, porro, ab sapiente, amet dolorem repudiandae voluptatem inventore.",
    para2: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia doloremque ut ex, itaque omnis optio dolore repellat quam unde accusamus pariatur cupiditate, nihil rerum delectus sed placeat adipisci necessitatibus maxime eum incidunt nulla animi sequi. Quas fuga voluptate magnam odio error laborum, porro, ab sapiente, amet dolorem repudiandae voluptatem inventore.",
  },
  {
    title: "flaskPresent",
    link: "https://flaskpresent.krzem.dev/",
    code: "https://github.com/krzemGit/flaskTemplates",
    design: "https://www.dropbox.com/s/s4gcsu7xfu5uex5/flask_present_full.jpg?raw=1",
    tech: "Python / Flask / Javascript / SQLite",
    para1: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia doloremque ut ex, itaque omnis optio dolore repellat quam unde accusamus pariatur cupiditate, nihil rerum delectus sed placeat adipisci necessitatibus maxime eum incidunt nulla animi sequi. Quas fuga voluptate magnam odio error laborum, porro, ab sapiente, amet dolorem repudiandae voluptatem inventore.",
    para2: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia doloremque ut ex, itaque omnis optio dolore repellat quam unde accusamus pariatur cupiditate, nihil rerum delectus sed placeat adipisci necessitatibus maxime eum incidunt nulla animi sequi. Quas fuga voluptate magnam odio error laborum, porro, ab sapiente, amet dolorem repudiandae voluptatem inventore.",
  },
  {
    title: "flaskCredit",
    link: "https://flaskcredit.krzem.dev/",
    code: "https://github.com/krzemGit/flask_credit",
    design: "https://www.dropbox.com/s/b9xftn3ij71f2j9/flask_credit.jpg?raw=1",
    tech: "Python / Flask / Javascript / SQLite",
    para1: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia doloremque ut ex, itaque omnis optio dolore repellat quam unde accusamus pariatur cupiditate, nihil rerum delectus sed placeat adipisci necessitatibus maxime eum incidunt nulla animi sequi. Quas fuga voluptate magnam odio error laborum, porro, ab sapiente, amet dolorem repudiandae voluptatem inventore.",
    para2: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia doloremque ut ex, itaque omnis optio dolore repellat quam unde accusamus pariatur cupiditate, nihil rerum delectus sed placeat adipisci necessitatibus maxime eum incidunt nulla animi sequi. Quas fuga voluptate magnam odio error laborum, porro, ab sapiente, amet dolorem repudiandae voluptatem inventore.",
  },
  {
    title: "bitInfo",
    link: "https://bit-info-30y7d1biy.vercel.app/",
    code: "https://github.com/krzemGit/bitInfo",
    design: "https://www.krzem.dev/no-mockup",
    tech: "React.js / Next.js / SASS / BEM / API",
    para1: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia doloremque ut ex, itaque omnis optio dolore repellat quam unde accusamus pariatur cupiditate, nihil rerum delectus sed placeat adipisci necessitatibus maxime eum incidunt nulla animi sequi. Quas fuga voluptate magnam odio error laborum, porro, ab sapiente, amet dolorem repudiandae voluptatem inventore.",
    para2: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia doloremque ut ex, itaque omnis optio dolore repellat quam unde accusamus pariatur cupiditate, nihil rerum delectus sed placeat adipisci necessitatibus maxime eum incidunt nulla animi sequi. Quas fuga voluptate magnam odio error laborum, porro, ab sapiente, amet dolorem repudiandae voluptatem inventore.",
  },
  {
    title: "waether-app",
    link: "https://weatherapp.krzem.dev/",
    code: "https://github.com/krzemGit/weather-app-cards",
    design: "https://www.dropbox.com/s/75ogop1yi1qqskv/polish_weather_app.jpg?dl=0",
    tech: "React.js / SASS / BEM / API",
    para1: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia doloremque ut ex, itaque omnis optio dolore repellat quam unde accusamus pariatur cupiditate, nihil rerum delectus sed placeat adipisci necessitatibus maxime eum incidunt nulla animi sequi. Quas fuga voluptate magnam odio error laborum, porro, ab sapiente, amet dolorem repudiandae voluptatem inventore.",
    para2: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia doloremque ut ex, itaque omnis optio dolore repellat quam unde accusamus pariatur cupiditate, nihil rerum delectus sed placeat adipisci necessitatibus maxime eum incidunt nulla animi sequi. Quas fuga voluptate magnam odio error laborum, porro, ab sapiente, amet dolorem repudiandae voluptatem inventore.",
  },
  {
    title: "infoService",
    link: "https://info-service.herokuapp.com/",
    code: "https://github.com/krzemGit/weather-app-cards",
    design: "https://www.krzem.dev/no-mockup",
    tech: "Node.js / Express / SASS / MongoDB",
    para1: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia doloremque ut ex, itaque omnis optio dolore repellat quam unde accusamus pariatur cupiditate, nihil rerum delectus sed placeat adipisci necessitatibus maxime eum incidunt nulla animi sequi. Quas fuga voluptate magnam odio error laborum, porro, ab sapiente, amet dolorem repudiandae voluptatem inventore.",
    para2: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia doloremque ut ex, itaque omnis optio dolore repellat quam unde accusamus pariatur cupiditate, nihil rerum delectus sed placeat adipisci necessitatibus maxime eum incidunt nulla animi sequi. Quas fuga voluptate magnam odio error laborum, porro, ab sapiente, amet dolorem repudiandae voluptatem inventore.",
  },
  {
    title: "starTrekCrew",
    link: "https://star-trek-crew.herokuapp.com/",
    code: "https://www.krzem.dev/no-mockup",
    design: "https://www.krzem.dev/no-mockup",
    tech: "JavaScript / Node.js / Express.js",
    para1: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia doloremque ut ex, itaque omnis optio dolore repellat quam unde accusamus pariatur cupiditate, nihil rerum delectus sed placeat adipisci necessitatibus maxime eum incidunt nulla animi sequi. Quas fuga voluptate magnam odio error laborum, porro, ab sapiente, amet dolorem repudiandae voluptatem inventore.",
    para2: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia doloremque ut ex, itaque omnis optio dolore repellat quam unde accusamus pariatur cupiditate, nihil rerum delectus sed placeat adipisci necessitatibus maxime eum incidunt nulla animi sequi. Quas fuga voluptate magnam odio error laborum, porro, ab sapiente, amet dolorem repudiandae voluptatem inventore.",
  },
  {
    title: "nodeServer",
    link: "http://node-serv1.herokuapp.com/",
    code: "https://github.com/krzemGit/nodeServer",
    design: "https://www.krzem.dev/no-mockup",
    tech: "Node.js / JavaScript",
    para1: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia doloremque ut ex, itaque omnis optio dolore repellat quam unde accusamus pariatur cupiditate, nihil rerum delectus sed placeat adipisci necessitatibus maxime eum incidunt nulla animi sequi. Quas fuga voluptate magnam odio error laborum, porro, ab sapiente, amet dolorem repudiandae voluptatem inventore.",
    para2: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia doloremque ut ex, itaque omnis optio dolore repellat quam unde accusamus pariatur cupiditate, nihil rerum delectus sed placeat adipisci necessitatibus maxime eum incidunt nulla animi sequi. Quas fuga voluptate magnam odio error laborum, porro, ab sapiente, amet dolorem repudiandae voluptatem inventore.",
  },
  {
    title: "nodeQuest",
    link: "https://nodequest.krzem.dev/",
    code: "https://github.com/krzemGit/express-quiz",
    design: "https://www.dropbox.com/s/zzdb0eqwf71v7vw/nodeQuest.jpg?raw=1",
    tech: "Node.js / Express.js / MongoDB / JavaScript / BEM",
    para1: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia doloremque ut ex, itaque omnis optio dolore repellat quam unde accusamus pariatur cupiditate, nihil rerum delectus sed placeat adipisci necessitatibus maxime eum incidunt nulla animi sequi. Quas fuga voluptate magnam odio error laborum, porro, ab sapiente, amet dolorem repudiandae voluptatem inventore.",
    para2: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia doloremque ut ex, itaque omnis optio dolore repellat quam unde accusamus pariatur cupiditate, nihil rerum delectus sed placeat adipisci necessitatibus maxime eum incidunt nulla animi sequi. Quas fuga voluptate magnam odio error laborum, porro, ab sapiente, amet dolorem repudiandae voluptatem inventore.",
  },
  {
    title: "Jackpot",
    link: "https://krzemgit.github.io/jackpot/",
    code: "https://github.com/krzemGit/jackpot",
    design: "https://www.dropbox.com/s/eotb3hjau41fw3o/jackpot.jpg?dl=0",
    tech: "Node.js",
    para1: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia doloremque ut ex, itaque omnis optio dolore repellat quam unde accusamus pariatur cupiditate, nihil rerum delectus sed placeat adipisci necessitatibus maxime eum incidunt nulla animi sequi. Quas fuga voluptate magnam odio error laborum, porro, ab sapiente, amet dolorem repudiandae voluptatem inventore.",
    para2: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia doloremque ut ex, itaque omnis optio dolore repellat quam unde accusamus pariatur cupiditate, nihil rerum delectus sed placeat adipisci necessitatibus maxime eum incidunt nulla animi sequi. Quas fuga voluptate magnam odio error laborum, porro, ab sapiente, amet dolorem repudiandae voluptatem inventore.",
  },
  {
    title: "rockPaper",
    link: "https://krzemgit.github.io/rock-paper-scissors/",
    code: "https://github.com/krzemGit/rock-paper-scissors",
    design: "https://www.krzem.dev/no-mockup",
    tech: "JavaScript / SASS / BEM",
    para1: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia doloremque ut ex, itaque omnis optio dolore repellat quam unde accusamus pariatur cupiditate, nihil rerum delectus sed placeat adipisci necessitatibus maxime eum incidunt nulla animi sequi. Quas fuga voluptate magnam odio error laborum, porro, ab sapiente, amet dolorem repudiandae voluptatem inventore.",
    para2: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia doloremque ut ex, itaque omnis optio dolore repellat quam unde accusamus pariatur cupiditate, nihil rerum delectus sed placeat adipisci necessitatibus maxime eum incidunt nulla animi sequi. Quas fuga voluptate magnam odio error laborum, porro, ab sapiente, amet dolorem repudiandae voluptatem inventore.",
  },
]

export default projectList;