[[redirects]]
from = "/"
to = "/index.html"

[[redirects]]
from = "/api/msg"
to = "https://portfolio-server-production-0dd6.up.railway.app/messages"
force = true
headers = {x-portfolio-id = "PORTFOLIO_ID"}